---
name: Test-WWW-Jaunt
version: 0.01_03
author:
  - Robert Krimen <robertkrimen@gmail.com>
abstract: A CGI-based testing platform.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  CGI: 0
  Carp: 0
  LWP: 0
  Path::Class: 0
  Test::HTML::Lint: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
  URI: 0
provides:
  Test::WWW::Jaunt:
    file: lib/Test/WWW/Jaunt.pm
    version: 0.01_03
  Test::WWW::Jaunt::Step:
    file: lib/Test/WWW/Jaunt/Step.pm
  Test::WWW::Jaunt::Test:
    file: lib/Test/WWW/Jaunt/Test.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
